---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wp-cm
   labels:
      app: wordpress

#$ kubectl.exe get all,mysql,pvc,pv -n wordpress
#...
#NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
#service/mysql                 ClusterIP   None             <none>        3306/TCP,9125/TCP   21m
#service/wpdb-mysql            ClusterIP   10.245.138.112   <none>        3306/TCP            67s

data:
   WORDPRESS_DB_HOST: wpdb-mysql.wordpress.svc.cluster.local
   WORDPRESS_DB_USER: root

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: wp-pvc
   labels:
      app: wordpress

spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
   storageClassName: do-block-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: wp-deploy
   labels:
      app: wordpress

spec:
   replicas: 1
   selector:
      matchLabels:
         app: wp-pod
   template:
      metadata:
         name: wp-pod
         labels:
            app: wp-pod
      spec:
         volumes:
         - name: wp-vol
           persistentVolumeClaim:
              claimName: wp-pvc

         containers:
         - name: wordpress
           image: wordpress
           imagePullPolicy: IfNotPresent
           envFrom:
           - configMapRef: 
               name: wp-cm
           env:
           - name: WORDPRESS_DB_PASSWORD
             valueFrom: 
               secretKeyRef:
                  name: wp-cluster-secret
                  key: ROOT_PASSWORD
           ports:
           - name: wp-port
             containerPort: 80
           volumeMounts:
           - name: wp-vol
             mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
   name: wp-svc
   labels:
      app: wordpress

spec:
   type: ClusterIP
   selector:
      app: wp-pod
   ports:
   - name: http-port
     port: 80
     targetPort: wp-port

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: wp-ing
   labels:
      app: wordpress
   annotations:
      kubernetes.io/ingress.class: "nginx"

spec:
   rules:
#$ kubectl.exe get svc -n nginx-ingress
#NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                      AGE
#nginx-ingress-controller             LoadBalancer   10.245.115.242   157.230.193.145   80:31896/TCP,443:32651/TCP   2d8h
   - host: "wordpress-157.230.193.145.nip.io"
     http:
        paths:
        - path: /
          backend:
             serviceName: wp-svc
             servicePort: http-port
